name: zitounas_voorraad
description: Zitounas voorraad - Flutter + Firebase
publish_to: "none"

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.8
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
